name: SIGPwny
author: SIGPwny
description: Cyber-security @ UIUC
github: //www.github.com/sigpwny
facebook: //www.facebook.com/groups/439995656109426
twitter: //www.twitter.com/sigpwny
email: jasmth14@illinois.edu

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
